modLoader = "javafml"
loaderVersion="${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/some-assembly-required/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/some-assembly-required"
logoFile="logo.png"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''

[[dependencies.some_assembly_required]]
    modId = "forge"
    mandatory = true
    versionRange="${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "create"
    mandatory = false
    versionRange = "${create_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "${farmersdelight_version_range}"
    ordering = "AFTER"
    side = "BOTH"
