modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/some-assembly-required/issues"

[[mods]]
modId = "some_assembly_required"
version = "${file.jarVersion}"
displayName = "Some Assembly Required"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/some-assembly-required"
logoFile = "logo.png"
authors = "ochotonida"
credits = "Loosely based on the fabric mod 'Sandwichable' by FoundationGames"
description = '''Design your own sandwiches!'''

[[dependencies.some_assembly_required]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "create"
    mandatory = false
    versionRange = "[0.5.1.a,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.19-1.1.2,)"
    ordering = "AFTER"
    side = "BOTH"
